const UpstairsBackRowMiddleSection = () => {
  return (
    <div className="flex flex-col gap-2 border-gray/50 rounded-lg p-5 relative items-center">
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">N</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">O</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">P</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">Q</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">R</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">S</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">T</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">U</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">V</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">W</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">X</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">Y</span>
      </div>
      <div className="flex gap-1 md:gap-2">
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <div className="w-3 h-3 md:w-5 md:h-5 bg-gray dark:bg-darkGray rounded-t-3xl hover:bg-yellow-500 hover:scale-110 transition-all  cursor-pointer"></div>
        <span className="dark:text-darkGray text-white text-sm">Z</span>
      </div>
    </div>
  );
};

export default UpstairsBackRowMiddleSection;
