name: Deploy to production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Copy files to the server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP_ADDRESS }}
          SERVER_USER: ${{ secrets.USERNAME }}
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'mkdir -p /root/theatreke.com-staging'
          scp -o StrictHostKeyChecking=no -r ./dist/* $SERVER_USER@$SERVER_IP:/root/theatreke.com-staging/
      - name: Run the application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP_ADDRESS }}
          SERVER_USER: ${{ secrets.USERNAME }}
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'cd /root/theatreke.com-staging &&  serve -s . -l 3000'
